/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const zi_scarr_sflight_assoc_Logic_OnRead = require('./code/zi_scarr_sflight_assoc-logic-OnRead');

class AppService extends LCAPApplicationService {
    async init() {

        this.on('READ', 'ZI_SCARR_SFLIGHT_ASSOC', async (request, next) => {
            await zi_scarr_sflight_assoc_Logic_OnRead(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    AppService
};